### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by szapp** [TheKetrab/G2-Ucieczka#2]
This repository is missing licenses for the GFA and CatInv. Since your source code is public, please stick to the license conditions. It is necessary to provide the license files in the source code.

A side note: CatInv was never meant to be part of any modification project as it is provided in a stand-alone patch. Please reconsider removing it from your modification. To quote the readme of CatInv:
> These scripts [...] were _**written exclusively for the patch**_ of the same name. Any substantial portions taken from this project must identify the original author and are subject to the terms of the MIT License.

**Comment by TheKetrab** [comment]
There was only a note in main README.md about the author. License files have been added to the appropriate directories. Thanks for paying attention to it.

**Comment by szapp** [comment]
Thanks for adding the notices! I think it will help others find the original source for documentation and help.
